/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cc
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private DefaultTableModel tableModel = null;

    public NewJFrame() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();   //获取当前屏幕大小
        Dimension frameSize = this.getPreferredSize();//获取当前窗口大小
        this.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);//保持窗口弹出位置居中
        tableModel = (DefaultTableModel) jTable1.getModel();
        DefaultTableCellRenderer r = new DefaultTableCellRenderer();
        r.setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        jTable1.setDefaultRenderer(Object.class, r);
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
        buttonGroup1.add(jRadioButton5);
        //限制只能输入数字  
        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int keyChar = e.getKeyChar();
                if ((keyChar >= KeyEvent.VK_0 && keyChar <= KeyEvent.VK_9) || (keyChar == KeyEvent.VK_DELETE)) {
                } else {
                    e.consume(); //关键，屏蔽掉非法输入  
                    JOptionPane.showMessageDialog(null, "请输入数字", "alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        jTextField2.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int keyChar = e.getKeyChar();
                if ((keyChar >= KeyEvent.VK_0 && keyChar <= KeyEvent.VK_9) || (keyChar == KeyEvent.VK_DELETE)) {
                } else {
                    e.consume(); //关键，屏蔽掉非法输入  
                    JOptionPane.showMessageDialog(null, "请输入数字", "alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        jTextField3.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int keyChar = e.getKeyChar();
                if ((keyChar >= KeyEvent.VK_0 && keyChar <= KeyEvent.VK_9) || (keyChar == KeyEvent.VK_DELETE)) {
                } else {
                    e.consume(); //关键，屏蔽掉非法输入  
                    JOptionPane.showMessageDialog(null, "请输入数字", "alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        jTextField4.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int keyChar = e.getKeyChar();
                if ((keyChar >= KeyEvent.VK_0 && keyChar <= KeyEvent.VK_9) || (keyChar == KeyEvent.VK_DELETE)) {
                } else {
                    e.consume(); //关键，屏蔽掉非法输入  
                    JOptionPane.showMessageDialog(null, "请输入数字", "alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        jTextField5.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int keyChar = e.getKeyChar();
                if ((keyChar >= KeyEvent.VK_0 && keyChar <= KeyEvent.VK_9) || (keyChar == KeyEvent.VK_DELETE)) {
                } else {
                    e.consume(); //关键，屏蔽掉非法输入  
                    JOptionPane.showMessageDialog(null, "请输入数字", "alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        jTextField6.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int keyChar = e.getKeyChar();
                if ((keyChar >= KeyEvent.VK_0 && keyChar <= KeyEvent.VK_9) || (keyChar == KeyEvent.VK_DELETE)) {
                } else {
                    e.consume(); //关键，屏蔽掉非法输入  
                    JOptionPane.showMessageDialog(null, "请输入数字", "alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("操作");

        jLabel1.setText("三角形三条边取值");

        jLabel2.setText("a");

        jLabel3.setText("b");

        jLabel4.setText("c");

        jTextField1.setText("1");

        jTextField3.setText("1");

        jTextField2.setText("100");

        jTextField4.setText("100");

        jTextField5.setText("1");

        jTextField6.setText("100");

        jLabel5.setText("～");

        jLabel6.setText("～");

        jLabel7.setText("～");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("测试用例生成方式");

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("边界值测试");

        jRadioButton2.setText("健壮性测试");

        jRadioButton3.setText("最坏情况测试");

        jRadioButton4.setText("健壮最坏情况测试");

        jRadioButton5.setText("随机测试");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel9.setText("测试显示");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "序号", "a", "b", "c", "输出结果"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.setToolTipText("");
        jPanel4.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("生成测试用例");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("清空");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("导出到excel表");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addGap(71, 71, 71)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(90, 90, 90))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText() == null || jTextField1.getText() == "" || jTextField1.getText().isEmpty() || jTextField2.getText() == null || jTextField2.getText() == "" || jTextField2.getText().isEmpty() || jTextField3.getText() == null || jTextField3.getText() == "" || jTextField3.getText().isEmpty() || jTextField4.getText() == null || jTextField4.getText().isEmpty() || jTextField4.getText() == "" || jTextField5.getText() == null || jTextField5.getText().isEmpty() || jTextField5.getText() == "" || jTextField6.getText() == null || jTextField6.getText().isEmpty() || jTextField6.getText() == "") {
            JOptionPane.showMessageDialog(null, "输入不能为空！", "alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Integer.parseInt(jTextField1.getText()) <= 0 || Integer.parseInt(jTextField2.getText()) <= 0 || Integer.parseInt(jTextField3.getText()) <= 0 || Integer.parseInt(jTextField4.getText()) <= 0 || Integer.parseInt(jTextField5.getText()) <= 0 || Integer.parseInt(jTextField6.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "请输入>0的数字", "alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Integer.parseInt(jTextField1.getText()) > Integer.parseInt(jTextField2.getText()) || Integer.parseInt(jTextField3.getText()) > Integer.parseInt(jTextField4.getText()) || Integer.parseInt(jTextField5.getText()) > Integer.parseInt(jTextField6.getText())) {
            JOptionPane.showMessageDialog(null, "开始不得大于终止", "alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int amin = Integer.parseInt(jTextField1.getText());
        int amax = Integer.parseInt(jTextField2.getText());
        int bmin = Integer.parseInt(jTextField3.getText());
        int bmax = Integer.parseInt(jTextField4.getText());
        int cmin = Integer.parseInt(jTextField5.getText());
        int cmax = Integer.parseInt(jTextField6.getText());
        //    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        //边界值测试
        if (jRadioButton1.isSelected()) {
            tableModel.setRowCount(0);
            String s = null;
            int a[] = {amin, amax, (amin + amax) / 2, amin + 1, amax - 1};
            int b[] = {bmin, bmax, (bmin + bmax) / 2, bmin + 1, bmax - 1};
            int c[] = {cmin, cmax, (cmin + cmax) / 2, cmin + 1, cmax - 1};
            int x = 0;
            for (int i = 0; i < a.length; i++) {
                int xb = (bmin + bmax) / 2;
                int xc = (cmin + cmax) / 2;
                if (a[i] + xb <= xc || a[i] + xc <= xb || xb + xc <= a[i]) {
                    s = "不构成三角形";
                } else {
                    if (a[i] == xb && xb == xc) {
                        s = "等边三角形";
                    } else {
                        if (a[i] == xb || a[i] == xc || xb == xc) {
                            s = "等腰三角形";
                        } else {
                            s = "普通三角形";
                        }
                    }

                }
                ++x;
                tableModel.addRow(new Object[]{x, a[i], xb, xc, s});

            }
            for (int i = 0; i < b.length; i++) {
                int xa = (amin + amax) / 2;
                int xc = (cmin + cmax) / 2;
                if (xa + b[i] <= xc || xa + xc <= b[i] || b[i] + xc <= xa) {
                    s = "不构成三角形";
                } else {
                    if (xa == b[i] && b[i] == xc) {
                        s = "等边三角形";
                    } else {
                        if (xa == b[i] || xa == xc || b[i] == xc) {
                            s = "等腰三角形";
                        } else {
                            s = "普通三角形";
                        }
                    }

                }
                ++x;
                tableModel.addRow(new Object[]{x, xa, b[i], xc, s});

            }
            for (int i = 0; i < c.length; i++) {
                int xb = (bmin + bmax) / 2;
                int xa = (amin + amax) / 2;
                if (xa + xb <= c[i] || xa + c[i] <= xb || xb + c[i] <= xa) {
                    s = "不构成三角形";
                } else {
                    if (xa == xb && xb == c[i]) {
                        s = "等边三角形";
                    } else {
                        if (xa == xb || xa == c[i] || xb == c[i]) {
                            s = "等腰三角形";
                        } else {
                            s = "普通三角形";
                        }
                    }

                }
                ++x;
                tableModel.addRow(new Object[]{x, xa, xb, c[i], s});

            }
        }
        if (jRadioButton2.isSelected()) {
            //健壮性测试
            tableModel.setRowCount(0);
            String s = null;
            int a[] = {amin - 1, amin, amax, amax + 1, (amin + amax) / 2, amin + 1, amax - 1};
            int b[] = {bmin - 1, bmin, bmax, amax + 1, (bmin + bmax) / 2, bmin + 1, bmax - 1};
            int c[] = {cmin - 1, cmin, cmax, amax + 1, (cmin + cmax) / 2, cmin + 1, cmax - 1};
            int x = 0;
            for (int i = 0; i < a.length; i++) {
                int xb = (bmin + bmax) / 2;
                int xc = (cmin + cmax) / 2;
                if (a[i] + xb <= xc || a[i] + xc <= xb || xb + xc <= a[i]) {
                    s = "不构成三角形";
                } else {
                    if (a[i] == xb && xb == xc) {
                        s = "等边三角形";
                    } else {
                        if (a[i] == xb || a[i] == xc || xb == xc) {
                            s = "等腰三角形";
                        } else {
                            s = "普通三角形";
                        }
                    }

                }
                ++x;
                tableModel.addRow(new Object[]{x, a[i], xb, xc, s});

            }
            for (int i = 0; i < b.length; i++) {
                int xa = (amin + amax) / 2;
                int xc = (cmin + cmax) / 2;
                if (xa + b[i] <= xc || xa + xc <= b[i] || b[i] + xc <= xa) {
                    s = "不构成三角形";
                } else {
                    if (xa == b[i] && b[i] == xc) {
                        s = "等边三角形";
                    } else {
                        if (xa == b[i] || xa == xc || b[i] == xc) {
                            s = "等腰三角形";
                        } else {
                            s = "普通三角形";
                        }
                    }

                }
                ++x;
                tableModel.addRow(new Object[]{x, xa, b[i], xc, s});

            }
            for (int i = 0; i < c.length; i++) {
                int xb = (bmin + bmax) / 2;
                int xa = (amin + amax) / 2;
                if (xa + xb <= c[i] || xa + c[i] <= xb || xb + c[i] <= xa) {
                    s = "不构成三角形";
                } else {
                    if (xa == xb && xb == c[i]) {
                        s = "等边三角形";
                    } else {
                        if (xa == xb || xa == c[i] || xb == c[i]) {
                            s = "等腰三角形";
                        } else {
                            s = "普通三角形";
                        }
                    }

                }
                ++x;
                tableModel.addRow(new Object[]{x, xa, xb, c[i], s});

            }
        }
        if (jRadioButton3.isSelected()) {
            //最坏情况测试
            tableModel.setRowCount(0);
            String s = null;
            int a[] = {amin, amax, (amin + amax) / 2, amin + 1, amax - 1};
            int b[] = {bmin, bmax, (bmin + bmax) / 2, bmin + 1, bmax - 1};
            int c[] = {cmin, cmax, (cmin + cmax) / 2, cmin + 1, cmax - 1};
            int x = 0;
            for (int i = 0; i < a.length; i++) {
                for (int j = 0; j < b.length; j++) {
                    for (int k = 0; k < c.length; k++) {
                        if (a[i] + b[j] <= c[k] || a[i] + c[k] <= b[j] || b[j] + c[k] <= a[i]) {
                            s = "不构成三角形";
                        } else {
                            if (a[i] == b[j] && b[j] == c[k]) {
                                s = "等边三角形";
                            } else {
                                if (a[i] == b[j] || a[i] == c[k] || b[j] == c[k]) {
                                    s = "等腰三角形";
                                } else {
                                    s = "普通三角形";
                                }
                            }

                        }
                        ++x;
                        tableModel.addRow(new Object[]{x, a[i], b[j], c[k], s});
                    }
                }
            }
        }
        if (jRadioButton4.isSelected()) {
            //健壮最坏情况测试
            tableModel.setRowCount(0);
            String s = null;
            int a[] = {amin - 1, amin, amax, amax + 1, (amin + amax) / 2, amin + 1, amax - 1};
            int b[] = {bmin - 1, bmin, bmax, amax + 1, (bmin + bmax) / 2, bmin + 1, bmax - 1};
            int c[] = {cmin - 1, cmin, cmax, amax + 1, (cmin + cmax) / 2, cmin + 1, cmax - 1};
            int x = 0;
            for (int i = 0; i < a.length; i++) {
                for (int j = 0; j < b.length; j++) {
                    for (int k = 0; k < c.length; k++) {
                        if (a[i] + b[j] <= c[k] || a[i] + c[k] <= b[j] || b[j] + c[k] <= a[i]) {
                            s = "不构成三角形";
                        } else {
                            if (a[i] == b[j] && b[j] == c[k]) {
                                s = "等边三角形";
                            } else {
                                if (a[i] == b[j] || a[i] == c[k] || b[j] == c[k]) {
                                    s = "等腰三角形";
                                } else {
                                    s = "普通三角形";
                                }
                            }

                        }
                        ++x;
                        tableModel.addRow(new Object[]{x, a[i], b[j], c[k], s});
                    }
                }
            }
        }
        if (jRadioButton5.isSelected()) {
            //随机测试
            tableModel.setRowCount(0);
            int x = 0;
            int ra, rb, rc;
            String s = null;
            for (int i = 0; i < 100; i++) {
                ra = (int) (amin + Math.random() * (amax - amin + 1));
                rb = (int) (bmin + Math.random() * (bmax - bmin + 1));
                rc = (int) (cmin + Math.random() * (cmax - cmin + 1));
                if (ra + rb <= rc || ra + rc <= rb || rb + rc <= ra) {
                    s = "不构成三角形";
                } else {
                    if (ra == rb && rb == rc) {
                        s = "等边三角形";
                    } else {
                        if (ra == rb || ra == rc || rb == rc) {
                            s = "等腰三角形";
                        } else {
                            s = "普通三角形";
                        }
                    }

                }
                ++x;
                tableModel.addRow(new Object[]{x, ra, rb, rc, s});
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //   IpExcel ie=new IpExcel(jTable1);
        ExportExcel ee = new ExportExcel(jTable1);
        ee.export();
        JOptionPane.showMessageDialog(null, "成功导出", "alert", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
